version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  
      - ./backend/database:/app/database  
    environment:
      - FLASK_ENV=development
      - SQLITE_DATABASE=/app/database/flights.db  
    command: flask run --host=0.0.0.0

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true
    tty: true
    depends_on:
      - backend  